import './globals.css'
import {ClusterProvider} from '@/components/cluster/cluster-data-access'
import {SolanaProvider} from '@/components/solana/solana-provider'
import {UiLayout} from '@/components/ui/ui-layout'
import {ReactQueryProvider} from './react-query-provider'
import { ChakraProvider } from '@chakra-ui/react'


export const metadata = {
  title: 'count',
  description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = [
  { label: 'Account', path: '/account' },
  { label: 'Clusters', path: '/clusters' },
  { label: 'Black Jack', path: '/blackjack' },
]

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ChakraProvider>
              <ClusterProvider>
                <SolanaProvider>
                  <UiLayout links={links}>{children}</UiLayout>
                </SolanaProvider>
              </ClusterProvider>
          </ChakraProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
